name: app
description: "Flutter structure"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

#--------------------Packages--------------------#
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  #Network
  dio: ^5.8.0+1
  retrofit: '>=4.0.0 <5.0.0'
  connectivity_plus: ^6.1.3

  #State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1

  #Local storage
  shared_preferences: ^2.5.2

  #Code generation
  #json_serializable: ^6.9.4
  #json_annotation: ^4.9.0
  #freezed: ^3.0.3
  #freezed_annotation: ^3.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  #Media
  image_picker: ^1.1.2
  video_player: ^2.9.3
  file_picker: ^10.0.0
  cached_network_image: ^3.4.1

  #UI & Animation
  flutter_svg: ^2.0.17
  animated_text_kit: 4.2.3
  flutter_animate: 4.5.2 
  lottie: ^3.3.1
  audioplayers: ^6.4.0
  syncfusion_flutter_gauges: ^29.1.33
  pinput: ^5.0.1
  flutter_staggered_grid_view: ^0.7.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  #flutter_spinkit 5.2.1
  
  #flutter_slidable: ^0.6.0
  #flutter_rating_bar: ^4.0.0
  #Utilites
  
  #Services
  geocoding: ^3.0.0
  permission_handler: ^11.4.0
  location: ^8.0.0
  sqflite: ^2.4.2

  #Helpers
  url_launcher: ^6.3.1
  go_router: ^14.8.1
  build_runner: ^2.4.15

  #After Creating the project
  supabase_flutter: ^2.8.4
  country_picker: ^2.0.27
  rounded_loading_button: ^2.1.0
  image_cropper: ^9.0.0
  uuid: ^4.5.1

#--------------------End Packages--------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: any
  riverpod_generator: any
  custom_lint:
  riverpod_lint: ^2.0.4

  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  generate: true
  uses-material-design: true

  #--------------------Local Assets--------------------#
  assets:
    - assets/images/
    - assets/fonts/
    - assets/sounds/
    - assets/lottie/
    - assets/svg/

flutter_assets:
  assets_path: assets/
  output_path: lib//core/constants/
  filename: assets.dart
